using SMG.Common.Effects;
using SMG.Common.Transitions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SMG.Common.Code
{
    /// <summary>
    /// Generates C# target code.
    /// </summary>
    public class CSharpCodeGenerator : CodeGenerator
    {
        #region Construction

        public CSharpCodeGenerator(CodeWriter writer)
            : base(writer)
        { }

        #endregion

        #region Overrides

        protected override void EmitPreamble()
        {
            Writer.AppendLine("/* class " + SM.Name + " generated by SMG */");
            Writer.AppendLine();

        }

        protected override void EmitEventTypeDeclaration()
        {
            EmitEnumeratedType(Parameters.EventTypeName, SM.Events.Select(e => e.Name));
        }

        protected override void EmitTypeDeclaration(string typename, IEnumerable<string> values)
        {
            EmitEnumeratedType(typename, values);
        }

        protected override void EmitClassHeader()
        {
            Writer.Append(Parameters.DefaultProtection + " class " + SM.Name);
            if (null != Parameters.BaseClassName)
            {
                Writer.Append(" : " + Parameters.BaseClassName);
                if (Parameters.IsBaseClassTemplate)
                {
                    Writer.Append("<" + Parameters.EventTypeName + ">");
                }
            }

            Writer.AppendLine();
        }

        protected override void EmitVariableDeclaration(Variable v)
        {
            Writer.AppendLine("private " + GetTypeID(v.Type) + " " + v.Name + ";");
        }

        protected override void EmitVariableAssignment(Variable v, int stateindex)
        {
            var stype = v.Type;

            Writer.Append(v.Name + " = ");

            if (stype.IsBoolean)
            {
                Writer.Append(stateindex == 0 ? "false" : "true");
            }
            else
            {
                Writer.Append(stype.Name + "." + stype.GetStateName(stateindex));
            }

            Writer.AppendLine(";");
        }

        protected override void EmitProcessEventMethodHeader()
        {
            Writer.AppendLine("protected virtual void ProcessEvent(" + Parameters.EventTypeName + " e)");
        }

        protected override void EmitHandlerHeader(string name)
        {
            Writer.AppendLine("protected virtual void " + name + "_Handler()");
        }

        protected override void EmitMethodDeclaration(string method)
        {
            Writer.AppendLine("protected virtual void " + method + "() { }");
        }

        protected override void EmitSwitchCaseLabel(Event e)
        {
            var caselabel = Parameters.EventTypeName + "." + e.Name;
            Writer.AppendLine("case " + caselabel + ":");
        }

        protected override void EmitEffect(Effect effect)
        {
            if(effect is CallEffect)
            {
                var call = (CallEffect)effect;
                Writer.AppendLine(call.MethodName + "();");
            }
            else if(effect is SendEffect)
            {
                var send = (SendEffect)effect;
                Writer.AppendLine("PostEvent(" + Parameters.EventTypeName + "." + send.Event.Name + ");");
            }
            else
            {
                throw new NotImplementedException("effect [" + effect + "] is not supported.");
            }
        }

        #endregion

        #region Private Methods

        private string GetTypeID(StateType stype)
        {
            return stype.IsBoolean ? "bool" : stype.Name;
        }

        private void EmitEnumeratedType(string typename, IEnumerable<string> values)
        {
            Writer.AppendLine(Parameters.DefaultProtection + " enum " + typename);
            Writer.EnterBlock();
            Writer.Append(values.ToSeparatorList());
            Writer.AppendLine();
            Writer.LeaveBlock();
            Writer.AppendLine();
        }

        private void EmitStateString(CodeWriter sb)
        {
            sb.AppendLine("public string ToStateString()");
            sb.EnterBlock();
            sb.AppendLine("var sb = new StringBuilder();");
            foreach (var v in SM.Variables)
            {
                sb.AppendLine("sb.Append(\" " + v.Name + "\" + \"(\");");
                sb.AppendLine("sb.Append(" + v.Name + ".ToString());");
                sb.AppendLine("sb.Append(\")\");");
            }

            sb.AppendLine("return sb.ToString();");
            sb.LeaveBlock();
            sb.AppendLine();

        }

        #endregion
    }
}
